/**
 * Chapter 1.5 §7.1 — interstage coupling capacitor.
 *
 * Topology (left → right):
 *   MIC (signal source, 0 V DC) — coupling C — +2 V DC bias node — AMP input
 *
 * The cap blocks the DC bias difference between the two stages (the
 * mic sits at 0 V, the amp input is held at +2 V for its operating
 * point), but passes the AC signal through. The amp's input DC bias
 * is generated by a resistor divider from V+ to GND — drawn here as
 * the two vertical resistors on the right, meeting at the amp input
 * node.
 *
 * Uses only `@/lib/circuit` primitives.
 */
import {
  Circuit,
  Wire,
  Junction,
  Resistor,
  Capacitor,
  TerminalLabel,
  pins2,
  SCHEMATIC_PAD_TOP,
  schematicHeight,
} from '@/lib/circuit'
import { useTranslation } from 'react-i18next'
import { MathText } from '@/components/ui/math-text'

const SCHEMATIC_W = 500

const TOP_Y = SCHEMATIC_PAD_TOP
const RAIL_SPAN = 130
const BOT_Y = TOP_Y + RAIL_SPAN
const SCHEMATIC_H = schematicHeight(RAIL_SPAN)

const SIG_Y = TOP_Y + 55 // signal rail (where mic → C → amp input runs)

// Terminal-column positions. Budgeted so the LEFT "МІК (0 В)" label
// (UA: ~80 px at 14 px italic Georgia) fits entirely inside the
// viewBox with its anchor='end' ending at MIC_X − 6, AND the right
// "ПДС" / "AMP" label fits starting at AMP_X + 6 within SCHEMATIC_W.
// Previous layout (MIC_X=60, AMP_X=410, W=520) clipped the left
// label off-canvas and left 90 px of empty space on the right.
const MIC_X = 110
const C_X = 220
const NODE_X = 330 // amp input node
const R1_X = NODE_X // R1 up from node to V+
const R2_X = NODE_X // R2 down from node to GND
const AMP_X = 440

const c = pins2(C_X, SIG_Y)
const r1 = pins2(R1_X, (TOP_Y + SIG_Y) / 2, 'down')
const r2 = pins2(R2_X, (SIG_Y + BOT_Y) / 2, 'down')

export default function CouplingCapSchematic() {
  const { t } = useTranslation('ui')

  return (
    <Circuit
      width={SCHEMATIC_W}
      height={SCHEMATIC_H}
      maxWidth={540}
      caption={<MathText>{t('ch1_5.couplingCapSchematicCaption')}</MathText>}
    >
      {/* V+ supply rail at the top (short stub on the right side) */}
      <Wire points={[{ x: R1_X, y: TOP_Y }, r1.p1]} />
      {/* GND rail at the bottom */}
      <Wire points={[{ x: R2_X, y: BOT_Y }, r2.p2]} />

      {/* Signal path: MIC terminal → C → node (where amp input sits) → AMP terminal */}
      <Wire points={[{ x: MIC_X, y: SIG_Y }, c.p1]} />
      <Wire points={[c.p2, { x: NODE_X, y: SIG_Y }, { x: AMP_X, y: SIG_Y }]} />

      {/* R1 from V+ rail down to amp input node */}
      <Wire points={[r1.p2, { x: R1_X, y: SIG_Y }]} />
      {/* R2 from amp input node down to GND */}
      <Wire points={[{ x: R2_X, y: SIG_Y }, r2.p1]} />

      {/* Components */}
      <Capacitor x={C_X} y={SIG_Y} label="C" />
      <Resistor x={R1_X} y={(TOP_Y + SIG_Y) / 2} orient="down" label="R_1" />
      <Resistor x={R2_X} y={(SIG_Y + BOT_Y) / 2} orient="down" label="R_2" />

      {/* T-junction: node where three wires meet (from C, from R1, to R2) */}
      <Junction x={NODE_X} y={SIG_Y} />

      {/* Terminal labels */}
      <TerminalLabel x={MIC_X - 6} y={SIG_Y} anchor="end">
        {t('ch1_5.couplingCapMic')}
      </TerminalLabel>
      <TerminalLabel x={AMP_X + 6} y={SIG_Y} anchor="start">
        {t('ch1_5.couplingCapAmp')}
      </TerminalLabel>
      <TerminalLabel x={R1_X + 8} y={TOP_Y} anchor="start">
        {t('ch1_5.couplingCapVplus')}
      </TerminalLabel>
      <TerminalLabel x={R2_X + 8} y={BOT_Y} anchor="start" tone="mutedFg">
        {t('ch1_5.couplingCapGnd')}
      </TerminalLabel>
    </Circuit>
  )
}
