/**
 * Solenoid geometry — labelled diagram of the four quantities that go
 * into the inductance formula L = µ₀·µᵣ·n²·A/l. The diagram sits above
 * the formula in the chapter so the reader can see what each symbol
 * physically represents:
 *
 *   • A    — cross-sectional area, shown as the round face on the left
 *            end of the cylinder (lightly tinted)
 *   • l    — length of the coil, shown as a dimension arrow below
 *   • n    — number of turns, with a leader line pointing to one wrap
 *   • µᵣ   — relative permeability of the core material, labelled
 *            inside the cylinder
 *
 * Geometry generated by Gemini 3.1 Pro (see
 * .claude/skills/illustrate/scripts/gemini-illustrate.py + the spec at
 * /tmp/solenoid_geometry_spec.json) and rendered AS-IS — no rough.js
 * wrap because that made earlier coil diagrams unreadable. Project
 * convention applied: fontFamily="inherit" so labels match the page's
 * IBM Plex Sans.
 */
import { useTranslation } from 'react-i18next'

export default function SolenoidGeometryDiagram() {
  const { t } = useTranslation('ui')

  return (
    <figure className="mx-auto my-4 max-w-[540px] not-prose">
      <svg
        viewBox="0 0 540 200"
        fill="none"
        aria-label={t('ch1_6.solenoidGeometryAria')}
        role="img"
        xmlns="http://www.w3.org/2000/svg"
        className="block w-full h-auto"
      >
        {/* Layer 1: Back passes of wires (BEHIND the core, faint) */}
        <g stroke="currentColor" strokeWidth="1" opacity="0.35" fill="none">
          <path d="M 150 135 C 160 135, 160 45, 170 45" />
          <path d="M 190 135 C 200 135, 200 45, 210 45" />
          <path d="M 230 135 C 240 135, 240 45, 250 45" />
          <path d="M 270 135 C 280 135, 280 45, 290 45" />
          <path d="M 310 135 C 320 135, 320 45, 330 45" />
          <path d="M 350 135 C 360 135, 360 45, 370 45" />
        </g>

        {/* Layer 2: Core occluder + outlines */}
        {/* Solid background fill so back passes are hidden inside the cylinder */}
        <path d="M 130 45 L 390 45 A 20 45 0 0 1 390 135 L 130 135 Z" fill="hsl(var(--background))" stroke="none" />
        {/* Left ellipse — the visible round face of the cylinder; tinted to
            make the cross-sectional area concrete */}
        <ellipse cx="130" cy="90" rx="20" ry="45" fill="hsl(var(--background))" stroke="none" />
        <ellipse cx="130" cy="90" rx="20" ry="45" fill="currentColor" opacity="0.08" stroke="none" />

        {/* Core outlines */}
        <g stroke="currentColor" strokeWidth="1.5" fill="none">
          <line x1="130" y1="45" x2="390" y2="45" />
          <line x1="130" y1="135" x2="390" y2="135" />
          <path d="M 390 45 A 20 45 0 0 1 390 135" />
          <ellipse cx="130" cy="90" rx="20" ry="45" />
        </g>

        {/* Centre axis (dashed) */}
        <g stroke="currentColor" strokeWidth="0.8" strokeDasharray="6 4" opacity="0.5" fill="none">
          <line x1="95" y1="90" x2="115" y2="90" />
          <line x1="145" y1="90" x2="305" y2="90" />
          <line x1="335" y1="90" x2="425" y2="90" />
        </g>

        {/* Layer 3: Front passes of wires + leads */}
        <g stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round">
          <path d="M 80 25 C 100 25, 110 45, 130 45" />
          <path d="M 130 45 C 140 45, 140 135, 150 135" />
          <path d="M 170 45 C 180 45, 180 135, 190 135" />
          <path d="M 210 45 C 220 45, 220 135, 230 135" />
          <path d="M 250 45 C 260 45, 260 135, 270 135" />
          <path d="M 290 45 C 300 45, 300 135, 310 135" />
          <path d="M 330 45 C 340 45, 340 135, 350 135" />
          <path d="M 370 45 C 380 45, 380 135, 390 135" />
          <path d="M 390 135 C 410 135, 420 155, 440 155" />
        </g>

        {/* Layer 4: Dimension line for length l */}
        <g stroke="currentColor" strokeWidth="0.8" fill="none">
          <line x1="130" y1="160" x2="130" y2="185" />
          <line x1="390" y1="160" x2="390" y2="185" />
          <line x1="130" y1="175" x2="390" y2="175" />
        </g>
        <path d="M 138 171 L 130 175 L 138 179 Z" fill="currentColor" stroke="none" />
        <path d="M 382 171 L 390 175 L 382 179 Z" fill="currentColor" stroke="none" />

        {/* Leader line for n-turns label */}
        <g stroke="currentColor" strokeWidth="0.8" fill="none">
          <path d="M 225 115 L 205 150 L 195 150" />
        </g>
        <circle cx="225" cy="115" r="2" fill="currentColor" stroke="none" />

        {/* Layer 5: Text labels */}
        <g fontFamily="inherit" fontSize="16" fill="currentColor" stroke="none">
          {/* A inside the round face */}
          <text x="130" y="95" textAnchor="middle" fontStyle="italic" fontWeight="700">A</text>

          {/* l above the dimension line */}
          <text x="260" y="170" textAnchor="middle" fontStyle="italic" fontWeight="700">l</text>

          {/* n turns leader */}
          <text x="190" y="154" textAnchor="end">
            <tspan fontStyle="italic" fontWeight="700">n</tspan>
            <tspan> {t('ch1_6.solenoidGeometryTurnsLabel')}</tspan>
          </text>

          {/* µᵣ inside the core */}
          <text x="320" y="95" textAnchor="middle" fontStyle="italic" fontWeight="700">
            μ<tspan dy="4" fontSize="0.75em">r</tspan>
          </text>
        </g>
      </svg>
    </figure>
  )
}
